export const preparationFormsAndDrinks = [
    { code: "1", name: "Agua Pura" },
    { code: "2", name: "Agua con azúcar" },
    { code: "3", name: "Refrescos sin azúcar" },
    { code: "4", name: "Refrescos con azúcar" },
    { code: "5", name: "Infusión sin azúcar (anís,té, otros semejantes)" },
    { code: "6", name: "Infusión con azúcar" },
    { code: "7", name: "Café sin azúcar" },
    { code: "8", name: "Café con azúcar" },
    { code: "9", name: "Jugo: fruta o verdura sin azúcar" },
    { code: "10", name: "Jugo: fruta o verdura con azúcar" },
    { code: "11", name: "Jugo/néctar envasado sin azúcar" },
    { code: "12", name: "Jugo/néctar envasado con azúcar" },
    { code: "13", name: "Leche sin azúcar" },
    { code: "14", name: "Leche con azúcar" },
    { code: "15", name: "Cereal/avena/soya/quinua sin leche sin azúcar" },
    { code: "16", name: "Cereal/avena/soya/quinua sin leche con azúcar" },
    { code: "17", name: "Cereal/avena/soya/quinua con leche sin azúcar" },
    { code: "18", name: "Cereal/savena/oya/quinua con leche con azúcar" },
    { code: "19", name: "Pan acompañamiento de frituras (pan con pollo y papas fritas / pan con mantequilla)" },
    { code: "20", name: "Pan acompañamiento sin frituras (pan, pan con queso , pan con palta)" },
    { code: "21", name: "Pan con embutido con y sin papaitas fritas" },
    { code: "22", name: "Sandwich/Hamburg. restaurante de comida rápida" },
    { code: "23", name: "Yogurt sin azúcar" },
    { code: "24", name: "Yogurt con azúcar" },
    { code: "25", name: "Yogurt con celeral natural" },
    { code: "26", name: "Yogurt con celeral azucarado" },
    { code: "27", name: "Caldo" },
    { code: "28", name: "Sopa casera" },
    { code: "29", name: "Ensalada de verduras (zanahoria, lechuga y tomate, palta)" },
    { code: "30", name: "Fruta entera/en trozos etc" },
    { code: "31", name: "Platos mixtos tradicionales con frituras (arroz con escabeche de pollo, Arroz con carne y papa frita)" },
    { code: "32", name: "Platos mixtos tradicionales sin frituras (adobo de pollo con ensalada, adobo de pollo con frijoles y arroz)" },
    { code: "33", name: "Guisos (estofado/saltado/verdura)" },
    { code: "34", name: "Frituras (pescado/carne/huevo/pollo/papa)" },
    { code: "35", name: "Fritura de restaurante de comida rápida" },
    { code: "36", name: "Cereal cocido (arroz, trigo, fideos, cancha tostada)" },
    { code: "37", name: "Frituras de preparaciones del colegio: Mostrito" },
    { code: "38", name: "Menestras (todo los tipos)" },
    { code: "39", name: "Galleta sin relleno" },
    { code: "40", name: "Galleta con relleno" },
    { code: "41", name: "Dulces, carmelos, chupetes, tofees" },
    { code: "42", name: "Bocaditos salados (tortees, papitas, chizitos)" },
    { code: "43", name: "Tortas /bocaditos dulces /mazamorra" },
    { code: "44", name: "Gaseosa regular (néctar en caja,  sporade, gaseosas / cifrut, chicha morada, refresco de gelatina)" },
    { code: "45", name: "Gaseosa zero" }
]